baseURL: ""
title: Ashish J. Galagali #website name 
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
#googleAnalytics: G-70EPC285RG5

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ashish J. Galagali 
  description: ""
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  # assets:
  #   # disableHLJS: true # to disable highlight.js
  #   # disableFingerprinting: true
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  params:
    assets:
      favicon: "/favicon.ico"
      favicon16x16:  "/favicon-16x16.png"
      favicon32x32:  "/favicon-32x32.png"
      apple_touch_icon:  "/apple-touch-icon.png"
      
  label:
    text: "Ashish J. Galagali"
    icon: 
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Ashish J. Galagali  
    subtitle: "This is subtitle"
    imageUrl: "/albert-einstein-quotes.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: > 
      I'm Ashish, student from earth. <p><span class="nowrap"><span class="emojify">🌎</span>  

      - This is my personal blog and also my briandump. (Disclaimer: I can't spell)

      - learn ⇄ imagine ⇆ build 

      - [My second brain](https://the-second-brain.super.site/)
      
      - [All my notes](https://checkered-flyingfish-fa7.notion.site/559a60ff18f8479591b169a399a5778e?v=89f48cf9b88744e2bb322d7e6e3ea009)


  socialIcons:
    - name: twitter
      url: "https://twitter.com/ashishjg_x"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/12134679/ashish-galagali"
    - name: github
      url: "https://github.com/ashishjg21"
    - name: linkedin
      url: "https://www.linkedin.com/in/ashish-galagali/"
    - name: email
      url: "mailto:ajg8188@gmail.com"
    - name: instagram
      url: "https://www.instagram.com/ashishjg"
    - name: cv
      url: "https://github.com/ashishjg21/my_cv/blob/main/ASHISH_J%20GALAGALI_Resume_07-07-2022-01-46-07.pdf"
    
    # google:
    #   SiteVerificationTag: "XYZabc"
    # bing:
    # analytics:    SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html

  outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url : /search 
      weight: 30
#Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        #anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

# taxonomies:
#     category: categories
#     tag: tags
#     series: series